services:
  db:
    image: postgres:16-alpine
    container_name: seatlock-db
    restart: always
    env_file:
      - database_local.env
    networks:
      - app-network
    ports:
      - "55434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d seatlock"]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.26
    container_name: seatlock-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - app-network
    ports:
      - "9200:9200"
    volumes:
      - elasticdata_v2:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: seatlock-api
    env_file:
      - database_local.env
      - security.env
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

networks:
  app-network:
    external: true

volumes:
  pgdata:
  elasticdata_v2: