// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: seats.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPurchasedSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPurchasedSeatsRequest) Reset() {
	*x = GetPurchasedSeatsRequest{}
	mi := &file_seats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchasedSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchasedSeatsRequest) ProtoMessage() {}

func (x *GetPurchasedSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchasedSeatsRequest.ProtoReflect.Descriptor instead.
func (*GetPurchasedSeatsRequest) Descriptor() ([]byte, []int) {
	return file_seats_proto_rawDescGZIP(), []int{0}
}

func (x *GetPurchasedSeatsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type GetPurchasedSeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatIds       []string               `protobuf:"bytes,1,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPurchasedSeatsResponse) Reset() {
	*x = GetPurchasedSeatsResponse{}
	mi := &file_seats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchasedSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchasedSeatsResponse) ProtoMessage() {}

func (x *GetPurchasedSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchasedSeatsResponse.ProtoReflect.Descriptor instead.
func (*GetPurchasedSeatsResponse) Descriptor() ([]byte, []int) {
	return file_seats_proto_rawDescGZIP(), []int{1}
}

func (x *GetPurchasedSeatsResponse) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

var File_seats_proto protoreflect.FileDescriptor

const file_seats_proto_rawDesc = "" +
	"\n" +
	"\vseats.proto\x12\x05seats\"5\n" +
	"\x18GetPurchasedSeatsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"6\n" +
	"\x19GetPurchasedSeatsResponse\x12\x19\n" +
	"\bseat_ids\x18\x01 \x03(\tR\aseatIds2e\n" +
	"\vSeatService\x12V\n" +
	"\x11GetPurchasedSeats\x12\x1f.seats.GetPurchasedSeatsRequest\x1a .seats.GetPurchasedSeatsResponseB^\n" +
	"\x17com.seatlock.grpc.seatsP\x01ZAgithub.com/minakdanCVUT/SP1Team/seatlock_sockets/internal/grpc/pbb\x06proto3"

var (
	file_seats_proto_rawDescOnce sync.Once
	file_seats_proto_rawDescData []byte
)

func file_seats_proto_rawDescGZIP() []byte {
	file_seats_proto_rawDescOnce.Do(func() {
		file_seats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seats_proto_rawDesc), len(file_seats_proto_rawDesc)))
	})
	return file_seats_proto_rawDescData
}

var file_seats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_seats_proto_goTypes = []any{
	(*GetPurchasedSeatsRequest)(nil),  // 0: seats.GetPurchasedSeatsRequest
	(*GetPurchasedSeatsResponse)(nil), // 1: seats.GetPurchasedSeatsResponse
}
var file_seats_proto_depIdxs = []int32{
	0, // 0: seats.SeatService.GetPurchasedSeats:input_type -> seats.GetPurchasedSeatsRequest
	1, // 1: seats.SeatService.GetPurchasedSeats:output_type -> seats.GetPurchasedSeatsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seats_proto_init() }
func file_seats_proto_init() {
	if File_seats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seats_proto_rawDesc), len(file_seats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seats_proto_goTypes,
		DependencyIndexes: file_seats_proto_depIdxs,
		MessageInfos:      file_seats_proto_msgTypes,
	}.Build()
	File_seats_proto = out.File
	file_seats_proto_goTypes = nil
	file_seats_proto_depIdxs = nil
}
